Fixes #334. SPM587FA21 last name added.
SPM587FA21/SCM587FA21 pull request #350
Opened 2021-11-01 21:03 UTC by SFA21SCM85L

2021-11-01 21:24 UTC, SPM587FA21 requested changes
Wrong pull request title
Wrong name format for report

2021-11-01 21:36 UTC, SPM587FA21 requested changes
Pull request title is incorrect

2021-11-01 21:42 UTC, SFA21SCM85L commented
Fixes #334. SFA21SCM85L last name added

2021-11-02 13:03 UTC, SPM587FA21 approved these changes

2021-11-02 13:03 UTC, SPM587FA21 approved these changes

2021-11-02 13:04 UTC, merged